FROM gradle:8.5-jdk21-alpine AS build
WORKDIR /app
COPY . .
RUN gradle backend:build --no-daemon

FROM openjdk:21-slim
WORKDIR /app
COPY --from=build /backend/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]