FROM node:23 AS build
WORKDIR /app
COPY frontend/ .
RUN npm install
RUN npm run build
RUN npm start

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
