### Login Request
POST http://localhost:8080/v1/customer/login
Content-Type: application/json
    
    {
    "username": "rogelio.becker",
    "password": "rogelio.becker"
    }



### Customer list

GET http://localhost:8080/v1/customer